FROM node:11

RUN npm install -g yarn
ADD yarn.lock /yarn.lock
WORKDIR /usr/src/app
ADD package.json /package.json
COPY package.json yarn.lock ./

RUN yarn install
COPY . ./
CMD [ "yarn", "run", "start"]