version: '3'

services:
  db:
      image: kiasaki/alpine-postgres:9.5
      environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
        - '5555:5432'
      container_name: 2eo_db
      volumes:
        - database:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: 2eo_redis

  api:
    build: ./api
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
      - DJANGO_SU_PASSWORD=${DJANGO_SU_PASSWORD}
    container_name: 2eo_api
    
  # frontend:
  #   build: ./frontend
  #   command: yarn start
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "80:80"
  #   container_name: 2eo_frontend

volumes:
  database: