# Generated by Django 2.0.7 on 2018-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=5)),
                ('sect', models.CharField(max_length=5)),
            ],
        ),
    ]
