# Generated by Django 2.1 on 2018-08-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180726_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
