# Generated by Django 2.1.1 on 2018-09-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180803_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
