# Generated by Django 2.1.8 on 2019-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_superuser_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inactive_sections',
            field=models.ManyToManyField(related_name='inactive_sections', to='core.section'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sections',
            field=models.ManyToManyField(related_name='sections', to='core.section'),
        ),
    ]
