# Generated by Django 2.2.2 on 2019-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190629_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_subscribed',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
